title: "Primeros pasos en R: Exploración básica y visualización de datos. "
description: Curso a dictarse en Facena en el mes de marzo del 2019
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
